### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'int android.content.res.TypedArray.getDimensionPixelSize(int, int)' on a null object reference

### ISSUE THREAD

**Issue by ductranit** [JorgeCastilloPrz/AndroidFillableLoaders#19]
hi, got a crash log from device HUAWEI like when load this view:
Fatal Exception: java.lang.RuntimeException: Unable to start activity 
```
ComponentInfo{com.mz.tkw/com.mz.tkwui.SplashActivity}: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.github.jorgecastillo.FillableLoader
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2638)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2720)
       at android.app.ActivityThread.access$900(ActivityThread.java:196)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5988)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Caused by android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.github.jorgecastillo.FillableLoader
       at android.view.LayoutInflater.inflate(LayoutInflater.java:561)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:437)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(SourceFile:292)
       at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:140)
       at com.mz.tkwui.SplashActivity.setContentView(SourceFile:51)
       at android.app.Activity.performCreate(Activity.java:6444)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2720)
       at android.app.ActivityThread.access$900(ActivityThread.java:196)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5988)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Caused by android.view.InflateException: Binary XML file line #10: Error inflating class com.github.jorgecastillo.FillableLoader
       at android.view.LayoutInflater.createView(LayoutInflater.java:672)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:862)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:537)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:437)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(SourceFile:292)
       at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:140)
       at com.magez.ScreenEffect.ui.activities.SplashActivity_.onCreate(SourceFile:40)
       at android.app.Activity.performCreate(Activity.java:6444)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2720)
       at android.app.ActivityThread.access$900(ActivityThread.java:196)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5988)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at android.view.LayoutInflater.createView(LayoutInflater.java:641)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:862)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:537)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:437)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(SourceFile:292)
       at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:140)
       at com.magez.ScreenEffect.ui.activities.SplashActivity_.setContentView(SourceFile:51)
       at com.magez.ScreenEffect.ui.activities.SplashActivity_.onCreate(SourceFile:40)
       at android.app.Activity.performCreate(Activity.java:6444)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2720)
       at android.app.ActivityThread.access$900(ActivityThread.java:196)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5988)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.res.TypedArray.getDimensionPixelSize(int, int)' on a null object reference
       at com.github.jorgecastillo.attributes.AttributeExtractorImpl.getStrokeWidth(SourceFile:72)
       at com.github.jorgecastillo.FillableLoader.initAttrs(SourceFile:139)
       at com.github.jorgecastillo.FillableLoader.(SourceFile)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at android.view.LayoutInflater.createView(LayoutInflater.java:641)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:862)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:537)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:437)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(SourceFile:292)
       at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:140)
       at com.magez.ScreenEffect.ui.activities.SplashActivity_.setContentView(SourceFile:51)
       at com.magez.ScreenEffect.ui.activities.SplashActivity_.onCreate(SourceFile:40)
       at android.app.Activity.performCreate(Activity.java:6444)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2720)
       at android.app.ActivityThread.access$900(ActivityThread.java:196)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5988)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
```
Is there any suggestion?

**Comment by amylinn** [comment]
Looks like the weakReference to `weakAttributeArray` gets `null` somehow https://github.com/JorgeCastilloPrz/AndroidFillableLoaders/blob/5d569d6782174472ac53ff6b659b1aa9d1230476/library/src/main/java/com/github/jorgecastillo/attributes/AttributeExtractorImpl.java#L52-L59 when calling `getDimensionPixelSize`
https://github.com/JorgeCastilloPrz/AndroidFillableLoaders/blob/5d569d6782174472ac53ff6b659b1aa9d1230476/library/src/main/java/com/github/jorgecastillo/attributes/AttributeExtractorImpl.java#L71-L74 .

I think there is more information necessary - which device exactly, how do you use it, etc. :)
