### ISSUE TITLE
github.jorgecastillo.svg.SvgPathParser.ParsePath()

### ISSUE THREAD

**Issue by reema07** [JorgeCastilloPrz/AndroidFillableLoaders#22]
I am new in Android Studio Development

could you please guide me how to resolve this error to find the null point of string path error in SvgPathParser class parsePath() function pathstring not found.

**Comment by aligkts** [comment]
I have same issues.I could not solve it.

**Comment by Letme** [comment]
Can you2 paste some code producing this or what did you follow when this appeared?

**Comment by aligkts** [comment]
val loaderBuilder= FillableLoaderBuilder()
var fillable=activity?.findViewById<FillableLoader>(R.id.fillableLoader)
val path= SvgPath.Bag.path
fillable=loaderBuilder.parentView(rootView as ViewGroup?)
        .svgPath(path)
        .layoutParams(params)
        .originalDimensions(970, 970)
        .strokeColor(Color.parseColor("#1c9ade"))
        .fillColor(Color.parseColor("#1c9ade"))
        .strokeDrawingDuration(2000)
        .clippingTransform( WavesClippingTransform())
        .fillDuration(10000)
        .build()

Kimden: Crt Mori
Gönderilme: 26 Şubat 2019 Salı 18:58
Kime: JorgeCastilloPrz/AndroidFillableLoaders
Bilgi: Ali Göktaş; Comment
Konu: Re: [JorgeCastilloPrz/AndroidFillableLoaders]github.jorgecastillo.svg.SvgPathParser.ParsePath() (#22)

Can you2 paste some code producing this or what did you follow when this appeared?

**Comment by aligkts** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at com.github.jorgecastillo.svg.SvgPathParser.parsePath(SvgPathParser.java:52)
        at com.github.jorgecastillo.FillableLoader.buildPathData(FillableLoader.java:374)
        at com.github.jorgecastillo.FillableLoader.onSizeChanged(FillableLoader.java:224)


and this is the error log cat
Kimden: Crt Mori
Gönderilme: 26 Şubat 2019 Salı 18:58
Kime: JorgeCastilloPrz/AndroidFillableLoaders
Bilgi: Ali Göktaş; Comment
Konu: Re: [JorgeCastilloPrz/AndroidFillableLoaders]github.jorgecastillo.svg.SvgPathParser.ParsePath() (#22)

Can you2 paste some code producing this or what did you follow when this appeared?

**Comment by Letme** [comment]
(I am not on computer but lets get more info).

Can you print/share the value of you path (SvgPath.Bag.path)? It seems like that is NULL...

**Comment by aligkts** [comment]
No,in debug mod,I checked that it is not null.


Kimden: Crt Mori
Gönderilme: 26 Şubat 2019 Salı 19:05
Kime: JorgeCastilloPrz/AndroidFillableLoaders
Bilgi: Ali Göktaş; Comment
Konu: Re: [JorgeCastilloPrz/AndroidFillableLoaders]github.jorgecastillo.svg.SvgPathParser.ParsePath() (#22)

(I am not on computer but lets get more info).
Can you print/share the value of you path (SvgPath.Bag.path)? It seems like that is NULL...

**Comment by aligkts** [comment]
Kimden: Crt Mori
Gönderilme: 26 Şubat 2019 Salı 19:05
Kime: JorgeCastilloPrz/AndroidFillableLoaders
Bilgi: Ali Göktaş; Comment
Konu: Re: [JorgeCastilloPrz/AndroidFillableLoaders]github.jorgecastillo.svg.SvgPathParser.ParsePath() (#22)

(I am not on computer but lets get more info).
Can you print/share the value of you path (SvgPath.Bag.path)? It seems like that is NULL...

**Comment by Letme** [comment]
(your replies are a bit messed since you reply on mails)

Ok, so since `public FillableLoaderBuilder svgPath(String svgPath)` takes String and you feed it with `val` we can start with that alignment. Here I assume that path contains something like string with "\n" for end of line characters, some string numbers with dots and stuff (so not OS path)...

**Comment by aligkts** [comment]
Yes my path is like that.I got it from repo sample

Kimden: Crt Mori
Gönderilme: 26 Şubat 2019 Salı 19:14
Kime: JorgeCastilloPrz/AndroidFillableLoaders
Bilgi: Ali Göktaş; Comment
Konu: Re: [JorgeCastilloPrz/AndroidFillableLoaders]github.jorgecastillo.svg.SvgPathParser.ParsePath() (#22)

(your replies are a bit messed since you reply on mails)
Ok, so since public FillableLoaderBuilder svgPath(String svgPath) takes String and you feed it with val we can start with that alignment. Here I assume that path contains something like string with "\n" for end of line characters, some string numbers with dots and stuff (so not OS path)...

**Comment by aligkts** [comment]
Yes my path contains "\n" and "+".What do you think?

**Comment by Letme** [comment]
Did you try to change the path variable from val to String? It seems like the length is somehow null and that hits the null pointer exception.

**Comment by aligkts** [comment]
It is already 'val path: String?'   when I change it to 'path: String?',this does not refers path 'val path= SvgPath.Bag.path'

**Comment by Letme** [comment]
I would indeed change `val path= SvgPath.Bag.path` to `String path= SvgPath.Bag.path` to make it more explicit. You confirmed with debugger that `path` then contains a proper string which is passed to svgPath()? Just go step by step with break points if logcat print messages are not revealing enough.

**Comment by aligkts** [comment]
In Kotlin language, `val path= SvgPath.Bag.path` refers to Java's `String path= SvgPath.Bag.path`

**Comment by aligkts** [comment]
Path does not comes null I checked that but I have no idea about what is the problem :(

**Comment by Letme** [comment]
Kotlin... huh I am indeed rusty. Can you again paste the LogCat error and a nicely formatted example? I was on Java, but this might be issue with Kotlin calling Java?

**Comment by aligkts** [comment]
`java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at com.github.jorgecastillo.svg.SvgPathParser.parsePath(SvgPathParser.java:52)
        at com.github.jorgecastillo.FillableLoader.buildPathData(FillableLoader.java:374)
        at com.github.jorgecastillo.FillableLoader.onSizeChanged(FillableLoader.java:224)`

this is LogCat error

**Comment by Letme** [comment]
So the error reads exactly what I said, but what you pasted before was `.build()` method - so I assume logcat marks that line as failure in your application? You will have to give a lot more information if you want me to help you debug this, because now I can only guess.

**Comment by aligkts** [comment]
[https://gist.github.com/aligkts/94722473e34f55b812c56ca1977f3b37](url)
[https://gist.github.com/aligkts/2f3c1f5ef55ba594fd84dad3d2adb99b](url)
[https://gist.github.com/aligkts/560b8c1da5b1a743fde3f8c8d3c93e50](url)

You can check it from these links easily.

**Comment by Letme** [comment]
OK few ideas (remember don't know Kotlin syntax or background so might be totally off):

- I assume you confirmed without this lines the fragment loads (put a textview in to start with), because I remember you have to inflate fragments and stuff like that
- Maybe a simple var string instead of enum class would do the trick (although I read over Kotlin help on enum class and it should return String like you say it does)
- For future you are missing fillableLoader.setOnStateChangeListener(this); later on, because I see your error originates from: com.github.jorgecastillo.FillableLoader.onSizeChanged(FillableLoader.java:224), which might also be something coming from onStateChange trigger in second loop (error is kinda short and does not map to your code so I am guessing again).
